name: Build and Deploy

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Make Maven wrapper executable
        run: chmod +x ./CreativePrint_backend/mvnw
        
      - name: Build with Maven
        run: |
          cd CreativePrint_backend
          ./mvnw clean package -DskipTests
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./CreativePrint_backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/creative-print-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/creative-print-backend:${{ github.sha }}
            
      - name: Deployment Success Message
        run: echo "✅ Build and deployment completed successfully!"